version: 0.0
os: linux
files:
    - source: /
      destination: /var/www/html/aim_fe
file_exists_behavior: OVERWRITE
hooks:
    BeforeInstall:
        - location: scripts/app_stop.sh
          timeout: 300
          runas: ec2-user
    AfterInstall:
        - location: scripts/app_start.sh
          timeout: 300
          runas: ec2-user
permissions:
    - object: /var/www/html/aim_fe
      owner: ec2-user
      group: apache
      type:
          - directory
          - file
