name: Enforce Stage Branch

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR source branch
        run: |
          if [ "${{ github.head_ref }}" != "stage" ]; then
            echo "Error: Pull requests to main must come from the stage branch."
            exit 1
          fi
