name: Enforce Dev to Stage Branch

on:
  pull_request:
    branches:
      - stage

jobs:
  check-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR source branch
        run: |
          if [ "${{ github.head_ref }}" != "development" ]; then
            echo "Error: Pull requests to stage must come from the dev branch."
            exit 1
          fi
